[build]
  command = "npm ci && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.19.5"
  NETLIFY = "true"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200

[functions]
  node_bundler = "esbuild"