[build]
  command = "npm run build"
  functions = "netlify/functions" 
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200

[functions]
  node_bundler = "esbuild"