[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "20.19.5"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200

[functions]
  node_bundler = "esbuild"