import {
  getDecksUser,
  getMatchesUser,
  getDeckDetails,
  getUsers,
  getDecks,
  getGroupsUser,
  getMatchInfo,
  getUsersGroup,
  newUser,
  createGroup,
  createDeck,
  newMatch,
  editDeck,
  deleteDeck,
  getGroupDetails,
  joinGroup,
  leaveGroup,
  deleteGroup,
  getUserGroupMembership,
} from "./auth";

export const server = {
  newUser,
  createGroup,
  createDeck,
  getUsers,
  getDecks,
  getGroupsUser,
  getMatchInfo,
  newMatch,
  getDecksUser,
  getMatchesUser,
  getDeckDetails,
  getUsersGroup,
  editDeck,
  deleteDeck,
  getGroupDetails,
  joinGroup,
  leaveGroup,
  deleteGroup,
  getUserGroupMembership,
};
